name: Broken link check workflow
on: [workflow_dispatch]

jobs:
  link-check:
    name: Link check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Scan for broken links
      uses: enkeyz/linkcheck@main